import web3 from "./web3";

const address = "0xa498a81224a76Af38B906249075a9f2404cAD1EF";

const abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
    signature: "constructor",
  },
  {
    inputs: [],
    name: "addConsortium",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xd333bedb",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "allArticleCIDs",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xe917ec7f",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "allDomains",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x1f21b04f",
  },
  {
    inputs: [],
    name: "articleCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x414e28b0",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "articlesByCid",
    outputs: [
      { internalType: "string", name: "title", type: "string" },
      { internalType: "address", name: "author", type: "address" },
      { internalType: "uint256", name: "votes", type: "uint256" },
      { internalType: "bool", name: "isVerified", type: "bool" },
      { internalType: "string", name: "domain", type: "string" },
      { internalType: "uint256", name: "elGamalSignature", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x17e1e280",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "articlesByTitle",
    outputs: [
      { internalType: "string", name: "title", type: "string" },
      { internalType: "address", name: "author", type: "address" },
      { internalType: "uint256", name: "votes", type: "uint256" },
      { internalType: "bool", name: "isVerified", type: "bool" },
      { internalType: "string", name: "domain", type: "string" },
      { internalType: "uint256", name: "elGamalSignature", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x58812930",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "consortiumMembers",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x1f49f6ed",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "contenders",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x8eb31d96",
  },
  {
    inputs: [{ internalType: "string[]", name: "cids", type: "string[]" }],
    name: "deleteArticlesByCIDs",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xeefca44e",
  },
  {
    inputs: [],
    name: "getAllArticleCIDs",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x6f6eae2f",
  },
  {
    inputs: [],
    name: "getTopPerformersForEachDomain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x85daa872",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "isDomainRegistered",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x1c452781",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x8da5cb5b",
  },
  {
    inputs: [
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string", name: "cid", type: "string" },
      { internalType: "string", name: "domain", type: "string" },
    ],
    name: "publishArticle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x5b2656eb",
  },
  {
    inputs: [
      { internalType: "string", name: "title", type: "string" },
      { internalType: "uint256", name: "versionIndex", type: "uint256" },
    ],
    name: "queryArticle",
    outputs: [
      { internalType: "address", name: "author", type: "address" },
      { internalType: "string", name: "retrievedTitle", type: "string" },
      { internalType: "string", name: "cid", type: "string" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "uint256", name: "votes", type: "uint256" },
      { internalType: "bool", name: "isVerified", type: "bool" },
      { internalType: "uint256", name: "versionNumber", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xea23c031",
  },
  {
    inputs: [
      { internalType: "string", name: "username", type: "string" },
      { internalType: "string", name: "passwd", type: "string" },
      { internalType: "string", name: "domain", type: "string" },
    ],
    name: "registerUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xd637dcfa",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "registeredUsers",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x7259e0f8",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "temporaryContenders",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x170dff08",
  },
  {
    inputs: [],
    name: "threshold",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x42cde4e8",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "topPerformersMap",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xb79e63a7",
  },
  {
    inputs: [],
    name: "totalRegisteredDomains",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xffd7a4d5",
  },
  {
    inputs: [
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string", name: "newCid", type: "string" },
    ],
    name: "updateArticle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x8f79e4f4",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "users",
    outputs: [
      { internalType: "string", name: "username", type: "string" },
      { internalType: "string", name: "passwd", type: "string" },
      { internalType: "bool", name: "isRegistered", type: "bool" },
      { internalType: "uint256", name: "performanceScore", type: "uint256" },
      { internalType: "bool", name: "isConsortiumMember", type: "bool" },
      { internalType: "string", name: "domain", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xa87430ba",
  },
  {
    inputs: [{ internalType: "string", name: "title", type: "string" }],
    name: "verifyArticle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x2b40c794",
  },
  {
    inputs: [{ internalType: "string", name: "title", type: "string" }],
    name: "voteArticle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x834d61ec",
  },
];

export default new web3.eth.Contract(abi, address);
